version: '3.8'

services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./config:/config
      - ./media:/media
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
      # Bluetooth support
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    restart: unless-stopped
    privileged: true
    network_mode: host
    devices:
      # Bluetooth device access
      - /dev/ttyUSB0:/dev/ttyUSB0  # ถ้ามี USB Bluetooth
      - /dev/ttyACM0:/dev/ttyACM0  # ถ้ามี ACM device
    environment:
      - TZ=Asia/Bangkok
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/run/dbus/system_bus_socket
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8123"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: MQTT Broker (Mosquitto)
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    environment:
      - TZ=Asia/Bangkok

  # Optional: Database (PostgreSQL)
  postgres:
    container_name: homeassistant-postgres
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: homeassistant
      POSTGRES_USER: homeassistant
      POSTGRES_PASSWORD: ${DB_PASSWORD:-homeassistant}
      TZ: Asia/Bangkok
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Optional: Grafana for advanced dashboards
  grafana:
    container_name: homeassistant-grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
      - TZ=Asia/Bangkok
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources

volumes:
  postgres_data:
    driver: local
  grafana_data:
    driver: local

# Networks (optional - เพื่อการจัดการที่ดีขึ้น)
networks:
  default:
    name: homeassistant-network
